// https://dev.twitch.tv/docs/authentication/scopes/

export const scopes = {
    channelModerate: 'channel:moderate',
    chatEdit: 'chat:edit',
    chatRead: 'chat:read',
    whispersRead: 'whispers:read',
    whispersEdit: 'whispers:edit',
    analyticsReadExtensions: 'analytics:read:extensions',
    analyticsReadGames: 'analytics:read:games',
    bitsRead: 'bits:read',
    channelEditCommercial: 'channel:edit:commercial',
    channelManageBroadcast: 'channel:manage:broadcast',
    channelReadCharity: 'channel:read:charity',
    channelManageExtensions: 'channel:manage:extensions',
    channelManageModerators: 'channel:manage:moderators',
    channelManagePolls: 'channel:manage:polls',
    channelManagePredictions: 'channel:manage:predictions',
    channelManageRaids: 'channel:manage:raids',
    channelManageRedemptions: 'channel:manage:redemptions',
    channelManageSchedule: 'channel:manage:schedule',
    channelManageVideos: 'channel:manage:videos',
    channelReadEditors: 'channel:read:editors',
    channelReadGoals: 'channel:read:goals',
    channelReadHypeTrain: 'channel:read:hype_train',
    channelReadPolls: 'channel:read:polls',
    channelReadPredictions: 'channel:read:predictions',
    channelReadRedemptions: 'channel:read:redemptions',
    channelReadStreamKey: 'channel:read:stream_key',
    channelReadSubscriptions: 'channel:read:subscriptions',
    channelReadVips: 'channel:read:vips',
    channelManageVips: 'channel:manage:vips',
    clipsEdit: 'clips:edit',
    moderationRead: 'moderation:read',
    moderatorManageAnnouncements: 'moderator:manage:announcements',
    moderatorManageAutomod: 'moderator:manage:automod',
    moderatorReadAutomodSettings: 'moderator:read:automod_settings',
    moderatorManageAutomodSettings: 'moderator:manage:automod_settings',
    moderatorManageBannedUsers: 'moderator:manage:banned_users',
    moderatorReadBlockedTerms: 'moderator:read:blocked_terms',
    moderatorManageBlockedTerms: 'moderator:manage:blocked_terms',
    moderatorManageChatMessages: 'moderator:manage:chat_messages',
    moderatorReadChatSettings: 'moderator:read:chat_settings',
    moderatorManageChatSettings: 'moderator:manage:chat_settings',
    moderatorReadChatters: 'moderator:read:chatters',
    moderatorReadFollowers: 'moderator:read:followers',
    moderatorReadShieldMode: 'moderator:read:shield_mode',
    moderatorManageShieldMode: 'moderator:manage:shield_mode',
    moderatorReadShoutouts: 'moderator:read:shoutouts',
    moderatorManageShoutouts: 'moderator:manage:shoutouts',
    userEdit: 'user:edit',
    userEditFollows: 'user:edit:follows',
    userManageBlockedUsers: 'user:manage:blocked_users',
    userReadBlockedUsers: 'user:read:blocked_users',
    userReadBroadcast: 'user:read:broadcast',
    userManageChatColor: 'user:manage:chat_color',
    userReadEmail: 'user:read:email',
    userReadFollows: 'user:read:follows',
    userReadSubscriptions: 'user:read:subscriptions',
    userManageWhispers: 'user:manage:whispers',
} as const;

export type Scope = (typeof scopes)[keyof typeof scopes];

export const allScopes = Object.values(scopes);
